### ISSUE TITLE
License of this codebase 

### ISSUE THREAD

**Issue by mukarramkhalid** [ryangjchandler/ryangjchandler.co.uk#149]
Hello Ryan,

I really like some front-end elements of ryangjchandler.co.uk.
So I just wanted to confirm, would it be OK if I fork it and re-use some of the front-end elements in a personal project?
Couldn't find any license with this codebase. 

Thank you,

**Comment by ryangjchandler** [comment]
Hi @mukarramkhalid, the code is open-source but there is no license since I don't want people to re-use the code in their own projects.

**Comment by mukarramkhalid** [comment]
Noted. Thanks.
